### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by PatrykSzwer** [Juicy/juicy-draggable#6]
When you try to visit http://juicy.github.io/juicy-draggable/
You will get page like this:
![image](https://user-images.githubusercontent.com/25042256/37090224-c99106a8-2203-11e8-992c-ffebbef23c1a.png)

**Comment by warpech** [comment]
@PatrykSzwer, @alshakero can this be closed now after PR #7 was done?

**Comment by alshakero** [comment]
Yes, I also released https://github.com/Juicy/juicy-draggable/releases/tag/1.0.0.
